# Stats

<div id="toc"></div>

In [1]:
import os, sys, glob
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
data = pd.read_csv('data/data.csv', header = None)
data

0         1         2        3        4       5
0  220158.2  176491.7  441836.0  35907.4  48308.1  1243.1
1  222924.4  170472.1  440202.6  36856.1  48070.5  1243.7
2  219749.8  176723.9  441400.6  35981.0  48464.2  1242.8
3  222537.8  170488.0  436882.5  37278.8  48493.9  1243.4
4  222924.4  170472.1  440202.6  36856.1  48246.0  1243.7
5  215977.3  171496.7  430090.5  36414.4  48079.4  1235.0

### mean

In [6]:
M = np.mean(data_frame,0)
M

0    220711.983333
1    172690.750000
2    438435.800000
3     36548.966667
4     48277.016667
5      1241.950000
dtype: float64

In [7]:
M = np.mean(data_frame,1)
M

0    153990.750000
1    153294.900000
2    153927.050000
3    152820.733333
4    153324.150000
5    150548.883333
dtype: float64

### Variance

In [30]:
S = np.var(data)
S

0    6.128813e+06
1    7.806033e+06
2    1.644189e+07
3    2.456034e+05
4    2.761761e+04
5    9.762500e+00
dtype: float64

In [31]:
S = np.var(data, 1)
S

0    2.269728e+10
1    2.253485e+10
2    2.263992e+10
3    2.217890e+10
4    2.252870e+10
5    2.144742e+10
dtype: float64

### standard diviation

In [29]:
S = np.std(data)
S

0    2475.644042
1    2793.927893
2    4054.859976
3     495.583927
4     166.185473
5       3.124500
dtype: float64

In [28]:
S = np.std(data,1)
S

0    150656.151980
1    150116.114898
2    150465.686219
3    148925.822403
4    150095.624861
5    146449.374208
dtype: float64

### mode

In [27]:
from scipy import stats

Mo = stats.mode(data)
Mo

ModeResult(mode=array([[ 222924.4,  170472.1,  440202.6,   36856.1,   48070.5,    1243.7]]), count=array([[2, 2, 2, 2, 1, 2]]))

In [26]:
from scipy import stats

Mo = stats.mode(data,1)
Mo

ModeResult(mode=array([[ 1243.1],
       [ 1243.7],
       [ 1242.8],
       [ 1243.4],
       [ 1243.7],
       [ 1235. ]]), count=array([[1],
       [1],
       [1],
       [1],
       [1],
       [1]]))

### range/ptp

In [13]:
np.max(data) - np.min(data)

0     6947.1
1     6251.8
2    11745.5
3     1371.4
4      423.4
5        8.7
dtype: float64

In [14]:
np.max(data, 1) - np.min(data,1)

0    440592.9
1    438958.9
2    440157.8
3    435639.1
4    438958.9
5    428855.5
dtype: float64

In [24]:
data

0         1         2        3        4       5
0  220158.2  176491.7  441836.0  35907.4  48308.1  1243.1
1  222924.4  170472.1  440202.6  36856.1  48070.5  1243.7
2  219749.8  176723.9  441400.6  35981.0  48464.2  1242.8
3  222537.8  170488.0  436882.5  37278.8  48493.9  1243.4
4  222924.4  170472.1  440202.6  36856.1  48246.0  1243.7
5  215977.3  171496.7  430090.5  36414.4  48079.4  1235.0

In [23]:
np.ptp(np.array(data), axis=0)

array([  6.94710000e+03,   6.25180000e+03,   1.17455000e+04,
         1.37140000e+03,   4.23400000e+02,   8.70000000e+00])

In [25]:
np.ptp(np.array(data), axis=1)

array([ 440592.9,  438958.9,  440157.8,  435639.1,  438958.9,  428855.5])

## Moments

### skewness

In [35]:
type(data)

pandas.core.frame.DataFrame

In [37]:
import scipy.stats as stats
stats.skew(data)

array([-0.87276925,  0.65938398, -1.2713098 , -0.00415422,  0.00854593,
       -1.74737307])

### kurtosis

In [34]:
import scipy.stats as stats
stats.kurtosis(data)

array([-0.50408789, -1.50289048,  0.13593456, -1.4103655 , -1.51714364,
        1.12455806])